(define (make-queue)
	(let ((body (cons '() '())))
		(define (empty?)
			(and (eq? (car body) '()) (eq? (cdr body) '())))
		(define (only-one-element?)
			(and (not (empty?)) (eq? (cdar body) '())))
		(define (push! new)
			(let ((new-cons (cons new '())))
				(if (empty?)
					((lambda ()
						(set-car! body new-cons)
						(set-cdr! body new-cons)))
					(let ((last (cdr body)))
						(set-cdr! last new-cons)
						(set-cdr! body new-cons)))))
		(define (pop!)
			(cond
				((empty?)
					'())
				((only-one-element?)
					(let ((result (car body)))
						(set-car! body '())
						(set-cdr! body '())
						(car result)))
				(else
					(let ((result (car body)))
						(set-car! body (cdr result))
						(car result)))))
		(define (dispacher sym oprand)
			(cond
				((eq? sym 'empty?) (empty?))
				((eq? sym 'push!) (push! oprand))
				((eq? sym 'pop!) (pop!))))
		dispacher))

(define (empty? queue) (queue 'empty? 0))
(define (push! queue oprand) (queue 'push! oprand))
(define (pop! queue) (queue 'pop! 0))
